# Blueprint Types Library Package Manifest
# Semantic type definitions and reusable workflows for hiivmind-blueprint

name: hiivmind-blueprint-lib
version: "3.1.1"
description: |
  Externalized type definitions and reusable workflows for hiivmind-blueprint.
  Provides 31 consequence types, 14 precondition types, 5 node types, and
  1 reusable workflow that can be referenced by URL.

repository: https://github.com/hiivmind/hiivmind-blueprint-lib
license: MIT

# Schema versions for each type system
schemas:
  consequence: "1.1"
  precondition: "1.0"
  node: "1.0"
  workflow: "1.0"

# Statistics
stats:
  total_types: 50
  consequence_types: 31
  precondition_types: 14
  node_types: 5
  workflows: 1

# Artifacts produced by releases
artifacts:
  - consequences/ # Index and type definitions
  - preconditions/ # Index and type definitions
  - nodes/ # Node type definitions
  - workflows/ # Reusable workflow definitions
  - execution/ # Execution engine semantics
  - resolution/ # Bootstrap loaders and fetch patterns
  - schema/ # JSON Schema definitions

# Compatibility
minimum_blueprint_version: "3.0.0"

# How to reference this package from a workflow
usage: |
  In your workflow.yaml:

  ```yaml
  definitions:
    source: hiivmind/hiivmind-blueprint-lib@v3.1.0
  ```

  This fetches types from raw GitHub URLs at runtime.

  Reference a reusable workflow:

  ```yaml
  detect_intent:
    type: reference
    workflow: hiivmind/hiivmind-blueprint-lib@v3.1.0:intent-detection
    context:
      arguments: "${arguments}"
      intent_flags: "${intent_flags}"
      intent_rules: "${intent_rules}"
    next_node: execute_dynamic_route
  ```
