# Action Node Type Definition
# Executes operations and routes based on success/failure

schema_version: "1.0"
category: core

nodes:
  - type: action
    description:
      brief: Executes operations and routes based on success/failure
      detail: |
        An action node executes a sequence of consequence operations. All actions
        must succeed for on_success routing; any failure triggers on_failure routing.

        Actions are executed in order. If any action fails, subsequent actions are
        skipped and the node routes to on_failure. If all succeed, routes to on_success.
      notes:
        - Actions execute sequentially in array order
        - First failure short-circuits remaining actions
        - Results can be stored in state.computed via store_as
        - Supports ${} interpolation in action parameters

    fields:
      - name: type
        type: string
        required: true
        value: "action"
        description: Node type discriminator

      - name: description
        type: string
        required: false
        description: Human-readable purpose for debugging and documentation

      - name: actions
        type: array
        items: consequence
        required: true
        min_items: 1
        description: |
          Array of consequence objects to execute. Each consequence must have a 'type'
          field matching a defined consequence type (e.g., set_flag, read_file, clone_repo).

      - name: on_success
        type: node_reference
        required: true
        description: Node or ending identifier to route to when all actions succeed

      - name: on_failure
        type: node_reference
        required: true
        description: Node or ending identifier to route to when any action fails

    execution:
      effect: |
        for action in node.actions:
          result = dispatch_consequence(action, state)
          if result.failed:
            log_failure(action, result.error)
            return route_to(node.on_failure)
          if action.store_as:
            state.computed[action.store_as] = result.value
        return route_to(node.on_success)
      state_reads:
        - Any fields referenced in action parameters via ${} interpolation
      state_writes:
        - "computed.${store_as}" for each action with store_as
        - Additional writes defined by individual consequence types

    examples:
      - title: Basic action chain
        yaml: |
          read_config:
            type: action
            description: Load and validate configuration
            actions:
              - type: read_file
                path: "config.yaml"
                store_as: config
              - type: set_flag
                flag: config_loaded
                value: true
            on_success: process_config
            on_failure: error_no_config
        explanation: |
          Reads config.yaml and stores result in state.computed.config, then sets
          the config_loaded flag. If file read fails, routes to error_no_config.

      - title: Action with evaluation
        yaml: |
          check_sources:
            type: action
            actions:
              - type: evaluate
                expression: "len(config.sources) == 0"
                set_flag: is_first_source
              - type: set_state
                field: source_count
                value: "${computed.config.sources.length}"
            on_success: route_by_source_count
            on_failure: error_evaluation

      - title: Git clone action
        yaml: |
          clone_repository:
            type: action
            description: Clone the source repository
            actions:
              - type: clone_repo
                url: "${computed.repo_url}"
                path: "${computed.clone_path}"
                branch: "${user_responses.branch}"
                store_as: clone_result
              - type: set_flag
                flag: repo_cloned
                value: true
            on_success: scan_docs
            on_failure: error_clone_failed

    related:
      - conditional
      - validation_gate
    since: "1.0.0"
