# Extension: Package Management Consequences
# Tool and package installation operations

schema_version: "1.1"
category: extensions/package
description: Package and tool installation consequences

consequences:
  # --------------------------------------------------------------------------
  # install_tool
  # --------------------------------------------------------------------------
  - type: install_tool
    description:
      brief: Install a CLI tool if not already available
      detail: |
        Attempts to install a CLI tool using an appropriate package manager
        or install command. Uses the tool registry for install hints, or
        accepts a custom install command. Skips installation if tool is
        already available.
      notes:
        - Checks if tool is already installed first
        - Uses registry install_hint if no custom command provided
        - Requires network access for installation
        - May require elevated permissions depending on install method

    parameters:
      - name: tool
        type: string
        required: true
        description: Name of the tool to install
        pattern: "^[a-zA-Z0-9_-]+$"
        interpolatable: false

      - name: install_command
        type: string
        required: false
        description: Custom install command (overrides registry hint)
        interpolatable: true

      - name: skip_if_available
        type: boolean
        required: false
        default: true
        description: Skip installation if tool already available
        interpolatable: false

    payload:
      kind: side_effect
      tool: Bash

      requires:
        network: true
        timeout_seconds: 300

      provides:
        features:
          - tool_installation
        outputs:
          - field: computed.install_result
            type: object
            description: Installation result with status and message

      effect: |
        # Check if already installed
        if skip_if_available and tool_available(tool):
          return { status: "skipped", message: "Tool already available" }

        # Get install command
        if install_command:
          cmd = interpolate(install_command)
        else:
          hint = registry_lookup(tool, "install_hint")
          if not hint:
            error("No install command for tool: " + tool)
          # Use first option from hint (e.g., "apt install X / brew install X")
          cmd = hint.split(" / ")[0]

        # Execute installation
        result = Bash(cmd)
        if result.exit_code != 0:
          error("Installation failed for " + tool + ": " + result.stderr)

        # Verify installation
        if not tool_available(tool):
          error("Tool not available after installation: " + tool)

        return { status: "installed", message: "Successfully installed " + tool }

      state_writes:
        - computed.install_result
      state_reads: []

    examples:
      - title: Install jq using registry hint
        yaml: |
          - type: install_tool
            tool: jq

      - title: Install with custom command
        yaml: |
          - type: install_tool
            tool: uv
            install_command: "curl -LsSf https://astral.sh/uv/install.sh | sh"

      - title: Force reinstall
        yaml: |
          - type: install_tool
            tool: yq
            skip_if_available: false

      - title: Install in workflow with version check
        yaml: |
          preconditions:
            - type: tool_version_gte
              tool: yq
              min_version: "4.0"
          nodes:
            - id: ensure_yq
              type: action
              description: Ensure yq 4.x is installed
              consequences:
                - type: install_tool
                  tool: yq
                  install_command: "snap install yq"
              skip_if:
                - type: tool_version_gte
                  tool: yq
                  min_version: "4.0"

    related:
      - tool_available
      - tool_version_gte
      - network_available
    since: "2.0.0"
